apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: next-sample-app-pipeline-run-
spec:
  pipelineRef:
    name: nextjs-pipeline
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: next-sample-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/yongjia-next-sample-app.git
    - name: image-repo
      value: quay.io/yong_jia_chan_ibm/next-sample-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
