apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: yongjia-nextjs-sample-app
  app.kubernetes.io/instance: yongjia-nextjs-sample-app
  app.kubernetes.io/name: yongjia-nextjs-sample-app
  app.openshift.io/runtime: js